### ISSUE TITLE
Violates Mojang's EULA

### ISSUE THREAD

**Issue by x0XP** [sudofox/xdolf#1]
This repository contains files directly from Minecraft itself which violates Mojang's EULA. This in-tern means that you are violating software distribution laws which is a criminal offence.

**Comment by sudofox** [comment]
Hello x0XP, thank you for your concern. I previously brought this same concern up with you in Discord, before your repository was made private. However, this repository is for archive purposes, left in the way that it was before you and Sgt. Pepper took the original one down, and will not be modified from the way it was then. I will, however, specify in the README.md that the GPL3 license you were using cannot be applied to the parts of the code that were generated from the MCP mappings.

**Comment by sudofox** [comment]
I have added a note in the README.md that the GPL3 licensing cannot be applied to the code generated by Mod Coder Pack's mappings.

**Comment by x0XP** [comment]
Adding a note doesn't cut it, uploading and/or distributing Mojang's own code is a violation of their EULA and this repo can be taken down, it happened with tons of repo's before. Therefore this is still an outstanding issue.

**Comment by ghost** [comment]
e
